services:
  postgres:
    image: postgres:16-alpine
    container_name: event-platform-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_MULTIPLE_DATABASES: "event_auth_db,event_user_db"
    ports:
      - "${DB_PORT:-5434}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-multi-db.sh:/docker-entrypoint-initdb.d/init-multi-db.sh:ro
    networks:
      - event-network

volumes:
  postgres_data:

networks:
  event-network:
    driver: bridge
